export const rooms = [
  {
    name: "Charming Studio < 10 Miles to Wells' Beaches!",
    pricePerNight: 168,
    description:
      "Discover the charming town of Wells, where a welcoming ambiance and nature's beauty await you! This fully equipped 1-bath studio is the perfect retreat, offering convenient access to nearby beaches like Wells Beach and Drakes Island Beach. You can also explore the Rachel Carson National Wildlife Refuge, a prime destination for wildlife enthusiasts, located just 8 miles away. Plus, the downtown area is only a short 10-minute drive from your cozy vacation spot.",
    address: "4667 Bicetown Street, New York, NY, 10004",
    guestCapacity: 1,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: false,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/ny4n2w1ubdnfktua8stg",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693135931/bookit/demo/ny4n2w1ubdnfktua8stg.jpg",
      },
      {
        public_id: "bookit/demo/ao7enhxobr0z1qyxgyki",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693135931/bookit/demo/ao7enhxobr0z1qyxgyki.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Picturesque 2-Story Farmhouse w/Private Hot Tub",
    pricePerNight: 242,
    description:
      "Enjoy plenty of room for your family or a large group at this scenic Wells home, ideal for a peaceful retreat in classic Maine style! Spend your days soaking up the sun on the nearby beaches, then return to a spacious backyard and orchard where the kids can run around, plus a patio with a gas grill perfect for summer afternoon barbecues.",
    address: "200 Olympic Dr, Stafford, VS, 22554",
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/gbabqnb7nzvc7gmmpcvg",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136060/bookit/demo/gbabqnb7nzvc7gmmpcvg.jpg",
      },
      {
        public_id: "bookit/demo/tvheutup1idr5wi0p5bq",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1694680598/bookit/demo/tvheutup1idr5wi0p5bq.jpg",
      },
    ],
    category: "Twins",
    reviews: [],
  },
  {
    name: "Downtown Portsmouth Private Getaway! Hot Tub",
    pricePerNight: 85,
    description:
      "Experience the ultimate location in Portsmouth! This beautifully furnished, spacious, and private home is perfect for exploring the city’s iconic sights and historic attractions. Nestled near the banks of the Piscataqua River, you’ll be just minutes from must-see spots like Strawbery Banke Museum, Prescott Park, the USS Albacore Museum, Market Square, and much more! This home offers both comfort and proximity to the vibrant charm of Portsmouth.",
    address: "3747 Parkway Street, Apple Valley, CA, 92307",
    guestCapacity: 3,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: false,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/nhhthdrrvaundinfnyxd",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136187/bookit/demo/nhhthdrrvaundinfnyxd.jpg",
      },
      {
        public_id: "bookit/demo/qsmprvvkshpwynqinz8i",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136187/bookit/demo/qsmprvvkshpwynqinz8i.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Spacious Suite in a quiet Boston neighborhood.",
    pricePerNight: 95,
    description:
      "Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.",
    address: "224 Cherry St, Buffalo, NY, 14202",
    guestCapacity: 6,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/ahxbixikavvrlokgf8jp",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/ahxbixikavvrlokgf8jp.jpg",
      },
      {
        public_id: "bookit/demo/m7hgvpqj6kbqjsma0gfy",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/m7hgvpqj6kbqjsma0gfy.jpg",
      },
      {
        public_id: "bookit/demo/inpn3k94tvsmdaun0dsj",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/inpn3k94tvsmdaun0dsj.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "Shangri-La Hotel, Washington",
    pricePerNight: 105,
    description:
      "Our spacious room is designed for relaxation and comfort. It features a luxurious queen bed along with a foldable sofa, ideal for 2-3 adults, with a maximum capacity of four. The room is elegantly decorated with sophisticated touches and comes with a private bathroom with a shower. Additional amenities include a smart TV, mini-fridge, desk, and seating area by the window, offering serene city views. Please note that the room is located on the upper floor, accessible by stairs only.",
    address: "4724  Mudlick Road, Yakima, WA, 98902",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/ir1705u1vtfgzvqqdfh2",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136765/bookit/demo/ir1705u1vtfgzvqqdfh2.jpg",
      },
      {
        public_id: "bookit/demo/o3ieyr8gltwhwccgqzia",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136765/bookit/demo/o3ieyr8gltwhwccgqzia.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Hotel Chimayo de Santa Fe Rooms",
    pricePerNight: 36,
    description:
      "The rooms reflect the rich cultural heritage of New Mexico with authentic Southwestern décor. Each room is designed with handcrafted wood furnishings, traditional Chimayo textiles, and local artwork that add to the rustic charm. Many rooms feature cozy fireplaces, private balconies, and spacious seating areas that create a welcoming, warm ambiance. Modern amenities such as flat-screen TVs, complimentary Wi-Fi, and luxurious bedding ensure comfort. Guests can enjoy views of the charming courtyard or the historic surroundings of downtown Santa Fe, while the central location makes it easy to explore local attractions.",
    address: "1029  Godfrey Street, Portland, OR, 97205",
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/hmvqt42lzdjc197ynrtk",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136789/bookit/demo/hmvqt42lzdjc197ynrtk.jpg",
      },
    ],
    category: "Twins",
    reviews: [],
  },
  {
    name: "Parrish Avenue Hotel",
    pricePerNight: 82,
    description:
      "Our Comfort Room is designed for relaxation and convenience, offering a comfortable double bed, modern furnishings, and a serene ambiance for a restful stay. Guests can enjoy a spacious, well-appointed bathroom with either a walk-in shower or bathtub, and amenities such as a flat-screen TV, mini-fridge, safe, and complimentary Wi-Fi. The room’s decor blends contemporary touches with warm, inviting tones, ensuring a peaceful retreat after exploring the vibrant city of Saint Louis.",
    address: "2645  Parrish Avenue, SAINT LOUIS, MO, 63116",
    guestCapacity: 5,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: false,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/aenyd4econmkcvyiyjkc",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136804/bookit/demo/aenyd4econmkcvyiyjkc.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "The Spa at Base Camp at Kerry Hotel",
    pricePerNight: 76,
    description:
      "Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.",
    address: "3118  Red Hawk Road, Garfield, MN, 56332",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/bwrnbs3sqzd6bbuyau47",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg",
      },
      {
        public_id: "bookit/demo/hhjpp67jiqyacv8gvmso",
        url: "http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
];
