export const rooms = [
  {
    name: "Godfrey Inn & Suites, Portland",
    pricePerNight: 210,
    description:
      "Located in the heart of Portland, the Godfrey Inn & Suites offers a tranquil and stylish retreat with modern comfort and local charm. Just steps away from the city’s vibrant downtown, this boutique hotel blends contemporary design with the laid-back vibe that Portland is known for. Guests can enjoy cityscape views from select rooms.",
    address: "1029 Godfrey Street, Portland, OR, 97205",
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "roomi/room/godfrey-inn_building",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/godfrey-inn_building",
      },
      {
        public_id: "roomi/room/godfrey-inn_room1",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/godfrey-inn_room1",
      },
      {
        public_id: "roomi/room/godfrey-inn_room2",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/godfrey-inn_room2",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Mountain View Chalet",
    pricePerNight: 185,
    description:
      "Nestled in the serene mountains, the Mountain View Chalet offers a perfect retreat for nature lovers. Enjoy panoramic views of the surrounding peaks and unwind in a cozy, alpine-inspired room. Ideal for couples or small families, with a private balcony to take in the fresh mountain air.",
    address: "304 Alpine Drive, Aspen, CO, 81611",
    guestCapacity: 3,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: false,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "roomi/room/mountain_view_chalet-building",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/mountain_view_chalet-building.jpeg",
      },
      {
        public_id: "roomi/room/mountain_view_chalet-room1",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/mountain_view_chalet-room1.jpeg",
      },
      {
        public_id: "roomi/room/riverside_cabin-building",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/riverside_cabin-building.jpeg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Riverside Cabin",
    pricePerNight: 150,
    description:
      "Escape to nature in this quaint riverside cabin. The rustic charm is complemented by modern amenities, including a fully equipped kitchenette and a cozy sitting area. Perfect for a peaceful getaway near the riverbanks, with fishing and hiking trails just steps away.",
    address: "44 River Lane, Gatlinburg, TN, 37738",
    guestCapacity: 4,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "roomi/room/riverside_cabin-building",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/riverside_cabin-building.jpeg"
      },
      {
        public_id: "roomi/room/riverside_cabin-room1",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/riverside_cabin-room1.jpeg",
      },
      {
        public_id: "roomi/room/riverside_cabin-room2",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/riverside_cabin-room2.jpeg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Ocean Breeze Room",
    pricePerNight: 230,
    description:
      "Wake up to stunning ocean views in the Ocean Breeze Room. This spacious room features large windows overlooking the shoreline and is equipped with modern amenities to ensure a comfortable stay. Enjoy direct beach access and a private balcony to soak in the sea breeze.",
    address: "255 Beachfront Drive, Miami, FL, 33139",
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "roomi/room/ocean_breeze-building",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/ocean_breeze-building?updatedAt=1729579225161",
      },
      {
        public_id: "roomi/room/ocean_breeze-room1",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/ocean_breeze-room1",
      },
      {
        public_id: "roomi/room/ocean_breeze-room2",
        url: "https://ik.imagekit.io/h4fizh/roomi/room/ocean_breeze-room2",
      },
    ],
    category: "Twins",
    reviews: [],
  },
  {
    name: "Cozy Retreat",
    pricePerNight: 120,
    description:
      "This intimate, cozy retreat is perfect for couples or solo travelers seeking a peaceful getaway. The room is thoughtfully decorated to offer a homey atmosphere and includes a private bathroom, free Wi-Fi, and a flat-screen TV. Enjoy a relaxing stay with easy access to the town’s attractions.",
    address: "19 Elm Street, Stowe, VT, 05672",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/stowe1",
        url: "http://res.cloudinary.com/demo/stowe1.jpg",
      },
      {
        public_id: "bookit/demo/stowe2",
        url: "http://res.cloudinary.com/demo/stowe2.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "Luxury Villa by the Sea",
    pricePerNight: 400,
    description:
      "Indulge in the ultimate luxury experience at this stunning villa by the sea. With spacious interiors, high-end furnishings, and a private pool, this villa offers everything you need for a lavish beachside vacation. The villa features three bedrooms, perfect for families or groups.",
    address: "77 Coastal Avenue, Malibu, CA, 90265",
    guestCapacity: 6,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/malibu1",
        url: "http://res.cloudinary.com/demo/malibu1.jpg",
      },
      {
        public_id: "bookit/demo/malibu2",
        url: "http://res.cloudinary.com/demo/malibu2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Urban Chic Loft",
    pricePerNight: 220,
    description:
      "This modern urban loft offers a stylish and contemporary escape in the heart of the city. With sleek décor, open spaces, and large windows, the loft is perfect for those who want to be close to the city’s best attractions while enjoying a luxurious stay. The loft comes equipped with a kitchenette and high-speed internet.",
    address: "201 Downtown Plaza, Los Angeles, CA, 90012",
    guestCapacity: 3,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/la1",
        url: "http://res.cloudinary.com/demo/la1.jpg",
      },
      {
        public_id: "bookit/demo/la2",
        url: "http://res.cloudinary.com/demo/la2.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "Tropical Paradise",
    pricePerNight: 310,
    description:
      "Escape to this tropical paradise and enjoy the beauty of the island. With lush gardens and stunning ocean views, this suite is ideal for honeymooners or anyone looking for a serene getaway. The room includes a private deck, an outdoor shower, and luxurious amenities.",
    address: "400 Palm Road, Honolulu, HI, 96815",
    guestCapacity: 4,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/honolulu1",
        url: "http://res.cloudinary.com/demo/honolulu1.jpg",
      },
      {
        public_id: "bookit/demo/honolulu2",
        url: "http://res.cloudinary.com/demo/honolulu2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Serenity Suite",
    pricePerNight: 175,
    description:
      "Relax in the Serenity Suite, a peaceful haven with modern amenities and a calming atmosphere. The room is equipped with a king-size bed, a spacious bathroom, and a seating area perfect for unwinding. Located in a quiet part of the city, it's ideal for those seeking tranquility.",
    address: "233 Quiet Lane, Savannah, GA, 31401",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/savannah1",
        url: "http://res.cloudinary.com/demo/savannah1.jpg",
      },
      {
        public_id: "bookit/demo/savannah2",
        url: "http://res.cloudinary.com/demo/savannah2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "City Lights Loft",
    pricePerNight: 250,
    description:
      "Enjoy stunning views of the city skyline from this chic and modern loft. Perfectly located for exploring downtown, this loft features large windows, a fully equipped kitchenette, and a comfortable living area. Ideal for couples or solo travelers looking to experience the vibrant city life.",
    address: "500 Skyline Avenue, Chicago, IL, 60611",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/chicago1",
        url: "http://res.cloudinary.com/demo/chicago1.jpg",
      },
      {
        public_id: "bookit/demo/chicago2",
        url: "http://res.cloudinary.com/demo/chicago2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Lakeside Haven",
    pricePerNight: 195,
    description:
      "Tucked away by the tranquil lakeshore, this room offers a peaceful escape with breathtaking views. The room is designed for relaxation with a cozy interior, comfortable bed, and private balcony overlooking the water. Ideal for couples or small families looking for a serene getaway.",
    address: "789 Lakeside Road, Lake Tahoe, CA, 96150",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/tahoe1",
        url: "http://res.cloudinary.com/demo/tahoe1.jpg",
      },
      {
        public_id: "bookit/demo/tahoe2",
        url: "http://res.cloudinary.com/demo/tahoe2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Rustic Cabin",
    pricePerNight: 130,
    description:
      "Get back to nature in this charming rustic cabin, offering a cozy and authentic stay in the heart of the forest. The cabin is furnished with wooden accents, a comfortable bed, and a small kitchenette. It's the perfect spot for those looking to unplug and enjoy a peaceful retreat.",
    address: "222 Forest Road, Big Bear, CA, 92315",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: false,
    isBreakfast: false,
    isAirConditioned: false,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/bigbear1",
        url: "http://res.cloudinary.com/demo/bigbear1.jpg",
      },
      {
        public_id: "bookit/demo/bigbear2",
        url: "http://res.cloudinary.com/demo/bigbear2.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "Beachfront Bliss",
    pricePerNight: 290,
    description:
      "Step out onto the beach from this stunning beachfront room, perfect for those seeking sun and sand. The room features a comfortable king-size bed, modern amenities, and a private terrace overlooking the ocean. A perfect blend of luxury and relaxation awaits you.",
    address: "123 Ocean Drive, Miami Beach, FL, 33139",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/miamibeach1",
        url: "http://res.cloudinary.com/demo/miamibeach1.jpg",
      },
      {
        public_id: "bookit/demo/miamibeach2",
        url: "http://res.cloudinary.com/demo/miamibeach2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Whimsical Treehouse",
    pricePerNight: 240,
    description:
      "Experience something truly unique at the Whimsical Treehouse. This magical escape offers a one-of-a-kind stay, nestled among the trees and complete with charming decor and modern amenities. Perfect for those looking for adventure and a bit of fantasy in their travels.",
    address: "89 Woodland Path, Asheville, NC, 28801",
    guestCapacity: 1,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/asheville1",
        url: "http://res.cloudinary.com/demo/asheville1.jpg",
      },
      {
        public_id: "bookit/demo/asheville2",
        url: "http://res.cloudinary.com/demo/asheville2.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "Tranquil Waterside Villa",
    pricePerNight: 350,
    description:
      "Overlooking a serene lake, this villa offers a tranquil retreat from the hustle and bustle of everyday life. Enjoy stunning water views, a private pool, and luxurious interiors, perfect for a peaceful vacation. This villa is ideal for families or groups seeking comfort and privacy.",
    address: "500 Lakeview Road, Orlando, FL, 32830",
    guestCapacity: 6,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/orlando1",
        url: "http://res.cloudinary.com/demo/orlando1.jpg",
      },
      {
        public_id: "bookit/demo/orlando2",
        url: "http://res.cloudinary.com/demo/orlando2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Seaside Sanctuary",
    pricePerNight: 270,
    description:
      "This seaside sanctuary provides the ultimate beach getaway, with modern amenities and easy access to the shore. Wake up to ocean views, relax on your private terrace, and enjoy the sound of the waves. Perfect for couples or small families looking for a peaceful retreat.",
    address: "601 Coastal Avenue, Monterey, CA, 93940",
    guestCapacity: 4,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "bookit/demo/monterey1",
        url: "http://res.cloudinary.com/demo/monterey1.jpg",
      },
      {
        public_id: "bookit/demo/monterey2",
        url: "http://res.cloudinary.com/demo/monterey2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Historic Manor",
    pricePerNight: 200,
    description:
      "Step back in time with a stay at this historic manor, where old-world charm meets modern luxury. The room features elegant furnishings, high ceilings, and a comfortable bed. Perfect for those looking to experience a bit of history with all the comforts of home.",
    address: "300 Heritage Lane, Charleston, SC, 29401",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      { public_id: "demo/portland1", url: "http://image1.jpg" },
      { public_id: "demo/portland2", url: "http://image2.jpg" },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "Charming Studio < 10 Miles to Wells' Beaches!",
    pricePerNight: 168,
    description:
      "Discover the charming town of Wells, where a welcoming ambiance and nature's beauty await you! This fully equipped 1-bath studio is the perfect retreat, offering convenient access to nearby beaches like Wells Beach and Drakes Island Beach.",
    address: "4667 Bicetown Street, New York, NY, 10004",
    guestCapacity: 1,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: false,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      { public_id: "demo/ny1", url: "http://image17.jpg" },
      { public_id: "demo/ny2", url: "http://image18.jpg" },
    ],
    category: "Single",
    reviews: [],
  },
];
