import "bootstrap/dist/css/bootstrap.css";

import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import { GlobalProvider } from "./GlobalProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Head from "./head";
import dbConnect from "@/backend/config/dbConnect";

export const metadata: Metadata = {
  title: "Roomi",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await dbConnect({ throwOnError: true });

  return (
    <html lang="en">
      <Head />
      <body>
        <GlobalProvider>
          <Header />
          {children}
          <Footer />
        </GlobalProvider>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></Script>
        <Script src="https://kit.fontawesome.com/de9bf0351c.js"></Script>
      </body>
    </html>
  );
}
